version: "3"
services:
  nama-service:
    container_name: gks-shoppu
    image: mirzaq19/temanhewan-api
    volumes:
      - ./src:/var/www/html
    env_file: .env
    dns:
      - 1.1.1.1
      - 1.0.0.1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - nginx-proxy-network

  mysql:
    image: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=25052002
      - MYSQL_DATABASE=gks_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
      - SERVICE_TAGS = dev
      - SERVICE_NAME = mysql
    networks:
      - nginx-proxy-network

networks:
  nginx-proxy-network:
    external: true
