version: "3"
services:
  nama-service:
    container_name: gks-shoppu
    image: dptsi/laravel-web-dev
    volumes:
      - ./src:/var/www/html
    env_file: .env
    dns:
      - 1.1.1.1
      - 1.0.0.1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - nginx-proxy-network

  mysql:
    container_name: pbkk-mysql
    image: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=gks-db
    networks:
      - nginx-proxy-network

networks:
  nginx-proxy-network:
    external: true
